# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b723bd296ac282d77ab2b67577c7c11d20f9e0a99d93b2d12364e57033ccbfb69c9f84ff48ca57c441cc169a9bb92ab50e02e4b2114ad754d3f28054a305540a

test:
  secret_key_base: 9fe013f423bc80026d1580397fb7f0e5e41c89a7cecf9a5ca17c4061d0152ed4ab738e22be1ba92f1e93ee78131e7bd659840bc98b375b14c08290dc1bc85125

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
